#### general settings
name: UnfoldKE_try_x2_setting2
use_tb_logger: true
model: blind
distortion: sr
scale: 2
gpu_ids: [3]
pca_matrix_path: ../../../pca_matrix/DCLS/pca_aniso_matrix_x2.pth

degradation:
  random_kernel: True
  ksize: 11
  code_length: 10
  sig_min: 0.6
  sig_max: 5
  rate_iso: 0
  random_disturb: true

#### datasets
datasets:
  train:
    name: DIV2K
    mode: GT
    dataroot_GT: /131-data/cctv-data/sjtu/yfu/DAN_codes/codes/data/DIV2K_Flickr2K/x4HR.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 16
    GT_size: 128
    LR_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2KRK
    mode: LQGT
    dataroot_GT: /home/yfu/data_yfu/DATASETS/DIV2KRK/gt_renamed
    dataroot_LQ: /home/yfu/data_yfu/DATASETS/DIV2KRK/lr_x2

#### network structures
network_G:
  which_model_G: UnfoldKE
  setting:
    nf: 64
    nb: 10
    ng: 5
    ksize: 11
    loop: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_E: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 2e3 #2e3

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2e3
